apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240110182745.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240110182745.0.0+build.02e9424
  releaseNotes: |
    Release v20240110182745.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-10-01-2024-12-43-41-647280915/where-for-dinner-my-apps-bundle@sha256:0865e4e83493f26b01b816e346e1cce26ca8eb6484f9c041268457ca5cc3d5fc
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

